### ISSUE TITLE
Halite III support

### ISSUE THREAD

**Issue by simc** [rlee287/Halite-II-Gym#4]
Hi,

I can't get this to work with halite 3. Any chance you could give me a tip?

I always get the following error:
```
Traceback (most recent call last):
  File "./hlt_gym/hlt_gym.py", line 96, in <module>
    main()
  File "./hlt_gym/hlt_gym.py", line 92, in main
    args.iterations, " ".join(add_args))
  File "/.../hlt_gym/compare_bots.py", line 70, in play_games
    winner = _determine_winner(match_output)
  File "/.../hlt_gym/compare_bots.py", line 20, in _determine_winner
    return next(line for line in game_result.splitlines()
StopIteration
```

Thanks 👍

**Comment by rlee287** [comment]
They completely changed the output format this year. When I create a gym for Halite III, I will make it a new repo and link to it here.

**Comment by simc** [comment]
Thanks a lot!

**Comment by rlee287** [comment]
The Halite III of this tool is now available at https://github.com/rlee287/Halite-III-Bot-Comparator.
